
import './globals.scss'
import Header from '@/components/header/Header_Alisa'
import NavbarWeather from '@/components/header/NavbarWeather_Alisa'
import Head from '@/components/header/Head_Alisa'
import Aos from './aos'
export const metadata = {
    title: 'World Time',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <Head/>
            <body>
                <Aos/>
                <Header/>
                <NavbarWeather/>
                {children}
            </body>
        </html>
    )
}
